### ISSUE TITLE
Hide Android OS status bar

### ISSUE THREAD

**Issue by burrage** [curiouslearning/CognitivePlayground#29]
**User Story**
As a tester,
I want the the Android OS status bar to be hidden ,
So that there is more screen real estate for the game UI.

**Acceptance Criteria**
Given that I am on any screen of the game,
When I view the game,
Then the Android OS status bar is not visible.

**Comment by micahrye** [comment]
Status bar should be no problem. Did not find any good pre-existing packages for hiding soft keys, should look more. Can do via java, requires writing a bridge. 

Status bar size: small
Soft keys: large (if I have to write the java-js bridge code)

**Comment by burrage** [comment]
Soft keys will now be a separate task and moved to future development work.

**Comment by burrage** [comment]
User Story and Acceptance Criteria updated to reflect change.
