### ISSUE TITLE
Add passcode protection to the admin interface & home button

### ISSUE THREAD

**Issue by burrage** [curiouslearning/CognitivePlayground#38]
**UPDATE 9/19**
Without discontinue rules and game timeouts for all games, we will need a way for the tester to get back to the homescreen via locking the homescreen button via this same mechanism. Basically, onPress() for both the admin interface and home button in all of the games should bring up this passcode input.

**User Story**
As a tester,
I want access to the admin interface to be password protected with the code 0122 and the ability to close out of the password input if pressed by accident,
So that a child is not able to access the admin interface.

**Acceptance Criteria**
Given that I am on the homescreen,
When I press the admin interface icon,
Then a keypad password prompt is displayed, checks for password 0122, and lets the user see the admin interface if the password was correct.

Given that I am on the homescreen,
When I press the admin interface icon,
Then I am able to close out the password prompt if I don't know the password.

Given that I am on the homescreen,
When I press the admin interface icon and input an incorrect password,
Then the password prompt closes and I am returned to the homescreen.

**Comment by micahrye** [comment]
Size: small

**Comment by micahrye** [comment]
implemented, default code is 1234

**Comment by burrage** [comment]
@micahrye There’s no way to exit if you don’t know the passcode?

Also please read the full task including the update. 

We need to connect the passcode to the home button in the games as well because we need to keep develop mode on due to other issues, unfortunately. 

This will require some logic between whether entering the passcode will take you into Prefs (if coming to the passcode screen via "User Prefs" button on the homescreen) or if the passcode will take you back to the homescreen if coming from a game.

Likewise, logic required on an exit button. If exiting the passcode screen that was accessed by pressing "User Prefs" from the homescreen then it should take you back to the homescreen. If exiting from the passcode screen that was accessed by pressing the home button in a game then it should take you back to the game.

**Comment by micahrye** [comment]
added exit to game launch screen. have not added to all game home buttons, just bc it will slow testing etc.
