### ISSUE TITLE
Update bee graphic in Bug Zap

### ISSUE THREAD

**Issue by burrage** [curiouslearning/CognitivePlayground#39]
**User Story**
As a child,
I want it to be clearer that I am not supposed to touch a new icon during the "bee" trials by seeing a stark visual change to the answer I was supposed to touch,
So that I can better understand the objective of stopping myself from touching an answer during this phase if a change to the answers occurs.

Asset to use:
https://drive.google.com/open?id=0B1Q2Y5s6EhXLWXl2SmZCMDBCQlE

**Acceptance Criteria**
Given that I am playing Bug Zap,
When I reach a bee trial and the bug was supposed to turn into a bee,
Then the new red sign is visible (without the bee graphic-- see comments below).

**Comment by micahrye** [comment]
Size: small

**Comment by burrage** [comment]
UCSF would like to remove the bee entirely and just have a red circle to make it clearer that the touch action should be halted.

Since we are no longer using the flying away animation this is a simple asset switch.

**Comment by burrage** [comment]
User story and Acceptance Criteria updated and new graphic uploaded to original task.

**Comment by micahrye** [comment]
done

**Comment by burrage** [comment]
Asset missing in commit to master.

**Comment by burrage** [comment]
Fine for now but circle is off center.

![off_center_circle](https://user-images.githubusercontent.com/5167186/30553491-5e2cb9ee-9c6f-11e7-9ae3-148bd4d812b1.jpg)

**Comment by burrage** [comment]
Circle still off center despite code change. We can play around with the offset again tonight but low priority.
