### ISSUE TITLE
Play stimuli audio file from "stimuliAudioFile" in JSON for blending_words section

### ISSUE THREAD

**Issue by burrage** [curiouslearning/CognitivePlayground#41]
**User Story**
As a tester,
I need the correct stimuli to be played from the "stimuliAudioFile" in the JSON during the blending_words section of the Claw game,
So that the child hears the unblended audio stimuli first before hearing the blended audio choices from each box.

**Acceptance Criteria**
Given that I am playing the blending_words section of the Claw game,
When a trial begins,
Then the audio file designated in the stimuliAudioFile field in the trial JSON is played and I am able to select the correct audio box.

**Comment by micahrye** [comment]
fixed.

**Comment by burrage** [comment]
Need to up the time given for allowing the stimuli to be spoken. Many of the later trials have audio overlapping as a result.

**Comment by micahrye** [comment]
Fixed, also increased delay time.

**Comment by burrage** [comment]
@micahrye The value you have for additionalTime is fine up until Set 5-- specifically "launch" onward-- and then the audio stimuli starts to overlap with the answers again.

For reference, the longest audio stimuli is about 5 seconds in length.

**Comment by micahrye** [comment]
Okay, obviously I need to look into a different solution. 
given I can reliable get the lenght/time data from the audio file I can use that to dynamicaly adjust addition time etc

**Comment by micahrye** [comment]
Fixed.
