### ISSUE TITLE
New thought bubble UI

### ISSUE THREAD

**Issue by burrage** [curiouslearning/CognitivePlayground#44]
**User Story**
As a child,
I want the animal to be thinking of the symbol key and a single symbol at a time,
So that there is a clearer association between the symbol key and the symbol so I can know what I am supposed to do.

**Acceptance Criteria**
Given that I am playing Symbol Digit Coding,
When I view the UI,
Then the new dual thought bubble displays in the UI and the symbol the monster is thinking of displays only 1 symbol at a time instead of 3.

**Comment by burrage** [comment]
Geoff is designing the dual thought bubble based on this mock: 
https://drive.google.com/file/d/0B1Q2Y5s6EhXLT1dFR0FONFNjczg/view?usp=sharing

**Comment by burrage** [comment]
Geoff is designing this right now.

**Comment by burrage** [comment]
New assets are here:
https://drive.google.com/drive/folders/0B93m3Ny2fcJBMHFfSlVzb2R0T1k

Reference for how the UI will look is here:
https://drive.google.com/file/d/0B1Q2Y5s6EhXLSXY5WWhKQjRZdTg/view?usp=sharing

**Comment by micahrye** [comment]
Currently the thought bubble and symbol key are always present. In the new design would they stay present or disappear when food drops and eating? 

Given current implementation there would be more work in making the media disappear etc. 

Size: small - medium

**Comment by burrage** [comment]
Definitely fine to leave the bubble, symbol key, and symbol present during eating animation.

For getting the food drop to the monster with the thought bubble obstruction we have a couple of choices:
A.) Take a different path around the bubble to the monster's mouth.
B.) Layer the food to pass behind the thought bubble.

Choice B is probably easiest and the bubble is far enough away from the monster's mouth that you'd be able to see the food come out the other side of it anyway?

**Comment by micahrye** [comment]
B did not look good, went with pass over thought bubble, can change. 

done.
