### ISSUE TITLE
Celebration animation for completing a game

### ISSUE THREAD

**Issue by burrage** [curiouslearning/CognitivePlayground#45]
**User Story**
As a child,
I want a celebration animation to play after I complete a game before being sent to the homescreen,
So that I feel motivated to continue and that I did a good job.

**Acceptance Criteria**
Given that I am playing any of the 8 games,
When I finish all the trials in a game,
Then the celebration animation will play.

Given that I am playing any of the 8 games and I don't do anything,
When the game times out and is going to return to the homescreen,
Then the celebration animation does not play.

**Comment by burrage** [comment]
We would like the game to transition to a new screen just for an animation before returning to the homescreen. 

The animation will be a combination of two sprites: 1.) the success animation of the animal from the game you were playing and 2.) a star appearing animation.

Geoff is designing the animation right now.

**Comment by micahrye** [comment]
Solution: 
Could make new celebration component for this that then automatically goes to home screen on completion. Mostly need new media. 

Size: small

**Comment by burrage** [comment]
Animation instructions are here:

![animation_instructions](https://user-images.githubusercontent.com/5167186/30429615-1a2fd722-9926-11e7-8ed1-0ea04d70c154.png)

Assets are here:

https://drive.google.com/drive/folders/0Bw0U_uE9FgXHMmdoMXZGcmI3U2c

**Comment by micahrye** [comment]
done, needs sound.

**Comment by burrage** [comment]
@micahrye Symbol Digit Coding game needs to link to CelebrationGame too.

**Comment by burrage** [comment]
Also doesn't use the backgrounds that Geoff provided?

**Comment by burrage** [comment]
Audio to use for celebration (can be looped):

https://drive.google.com/file/d/0B1Q2Y5s6EhXLRkpWX0tJS1owMDA/view?usp=sharing
