### ISSUE TITLE
Match by Shape/Color JSON change to accommodate thought bubble UI element

### ISSUE THREAD

**Issue by burrage** [curiouslearning/CognitivePlayground#51]
**User Story**
As a child,
I want certain trials to be flagged with a JSON field on whether the animal should be thinking of the food they like to eat and to display a thought bubble with the food they like to eat inside the bubble in the UI,
So that I can better understand which animals eat which items.

**Acceptance Criteria**
Given that I am playing Match by Shape/Color,
When I read in the JSON and look for a field that says whether the animal should be thinking of the item they would like to eat,
Then a UI element of a thought bubble with the food they like to eat should appear above the animal.

Additional clarification from Roeland:

- For match by shape, show a ‘greyed out’ version of the target food in the thought bubble.

1. Fruit - https://drive.google.com/open?id=0B1Q2Y5s6EhXLUDRBNjdoTWNCRTg
2. Can - https://drive.google.com/open?id=0B1Q2Y5s6EhXLXzcxX1BxcVZKUlk
3. Grass - https://drive.google.com/open?id=0B1Q2Y5s6EhXLcnEtTGNyN0hOOTg

- For consistency, show a colored non-food item in a thought bubble on match by color trials.

1. Red - https://drive.google.com/file/d/0B1Q2Y5s6EhXLUkdaaElHX3d2d3c/view?usp=sharing
2. Blue - https://drive.google.com/file/d/0B1Q2Y5s6EhXLcVZSS25iRllweTA/view?usp=sharing
3. Green - https://drive.google.com/file/d/0B1Q2Y5s6EhXLODlka195Y0tnRHc/view?usp=sharing
4. Yellow - https://drive.google.com/file/d/0B1Q2Y5s6EhXLQmhiNDNmODNUb0k/view?usp=sharing

**Comment by micahrye** [comment]
Solution:
Similar to claw game, will require new logic and control code. 

size: small - medium

**Comment by micahrye** [comment]
Implemented. 
JSON update, all trials now require the key "thought" if the value is an empty string "" no thought bubble will be shown. See the trials.json for this game for example.
