### ISSUE TITLE
Return child to the homescreen when completing a level in the Lit games

### ISSUE THREAD

**Issue by burrage** [curiouslearning/CognitivePlayground#52]
**User Story**
As a child,
I want the Claw game and Pick The Right Button to be broken up into shorter playtimes by, at the end of a level (eg. letter_name, letter_sound, sight_words, blending_words, receptive_vocabulary, and pseudo_word), playing the celebration animation and returning me to the homescreen after I complete a level and for the game to resume at the next level (if applicable) when I go back into the game,
So that I experience less play fatigue when playing the same game.

**Acceptance Criteria**
Given that I am playing the Claw game,
When I finish a level or hit a discontinue rule,
Then I am shown the celebration animation and taken back to the homescreen.

Given I have completed the letter_name, letter_sound, or sight_words levels in the Claw game,
When I am on the homescreen,
Then I should be able to go back into the Claw game to play the next level.

Given that I am playing the Pick The Right Button game,
When I finish a level or hit a discontinue rule,
Then I am shown the celebration animation and taken back to the homescreen.

Given I have completed the receptive_vocabulary level in the Pick The Right Button game,
When I am on the homescreen,
Then I should be able to go back into the Pick The Right Button game to play the next level.

Given that I have completed all the levels in the Claw game,
When I view the homescreen,
Then the Claw game's icon should be grayed out and non-selectable.

Given that I have completed all the levels in the Pick The Right Button game,
When I view the homescreen,
Then the Pick The Right Button game's icon should be grayed out and non-selectable.

Given that I have completed a level in either the Claw game or Pick The Right Button,
When I view the data report for that level,
Then the IN_APP_RESPONSE, IN_APP_LEVEL_SUMMARY, and IN_APP_SECTION data is still correctly reported.

**Comment by micahrye** [comment]
Solutions:
1) Simply exit game after each level. This will require persisting game level information that can be used on game starting. This would use AsyncStorage, it would require new logic for persisting. Also, it will require new logic for start, since AsyncStorage values would have to be first retrieved before the game can be correctly initialized to the level. 

size: medium - large

**Comment by micahrye** [comment]
Auto exit lit games after completion of trial. Trial info saved so that on next entry of game it will start on next trial. 

Limited testing.

**Comment by burrage** [comment]
@micahrye Both lit games don't continue on to the next level after completing a level. Just starts the first level over and over.

**Comment by micahrye** [comment]
fixed.

**Comment by burrage** [comment]
Low priority. Pick The Right Button will start the first trial of pseudoword before exiting to the homescreen.
