### ISSUE TITLE
Increase size of tappable answers for Bug Zap and Match by Shape/Color

### ISSUE THREAD

**Issue by burrage** [curiouslearning/CognitivePlayground#54]
**User Story**
As a child,
I want the tappable answer area in the games Bug Zap and Match By Shape/Color to be larger,
So that I have less difficulty with precisely pressing the object inside the hanging circle.

**Acceptance Criteria**
Given that I am playing Bug Zap and Match By Shape/Color,
When I touch an answer inside the circle,
Then it is easier to select the item.

Given that I am playing Bug Zap and Match By Shape/Color,
When I touch the answer inside the circle,
Then the selected response is still picked up correctly in data collection.

**Comment by micahrye** [comment]
1) The easiest solution would be to increase the size of the bugs etc. 
2) Another solutions would be to programattically increase the size of the touch region, this would require changes to AnimatedSprite and would require more dev. 

Plan: I will first test increasing size of images programmatically (1). 

size: small

**Comment by burrage** [comment]
Sounds right! We'll go for 1 and re-evaluate after fielding. I feel this should be what they're looking for though.

**Comment by micahrye** [comment]
done

**Comment by burrage** [comment]
This looks good in Bug Zap but don't see the change in Match by Shape/Color. Fine for now and move on to top item in To Do.

**Comment by micahrye** [comment]
increased for match by shape/color
